@host=http://localhost:5031

POST {{host}}/auth/register
Content-Type: application/json

{
    "fullName":"Jane Deo",
    "email": "jane@demo.com",
    "password": "Secure123",
    "driverLicenseNumber":"SDSAJKJASD",
    "Token":"askdkdsa_msadk"
    
}